[{u'address_components': [{u'long_name': u'1600',
                           u'short_name': u'1600',
                           u'types': [u'street_number']},
                          {u'long_name': u'Amphitheatre Parkway',
                           u'short_name': u'Amphitheatre Pkwy',
                           u'types': [u'route']},
                          {u'long_name': u'Mountain View',
                           u'short_name': u'Mountain View',
                           u'types': [u'locality', u'political']},
                          {u'long_name': u'Santa Clara County',
                           u'short_name': u'Santa Clara County',
                           u'types': [u'administrative_area_level_2',
                                      u'political']},
                          {u'long_name': u'California',
                           u'short_name': u'CA',
                           u'types': [u'administrative_area_level_1',
                                      u'political']},
                          {u'long_name': u'United States',
                           u'short_name': u'US',
                           u'types': [u'country', u'political']},
                          {u'long_name': u'94043',
                           u'short_name': u'94043',
                           u'types': [u'postal_code']}],
  u'formatted_address': u'1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA',
  u'geometry': {u'location': {u'lat': 37.4223513, u'lng': -122.0843662},
                u'location_type': u'ROOFTOP',
                u'viewport': {u'northeast': {u'lat': 37.4237002802915,
                                             u'lng': -122.0830172197085},
                              u'southwest': {u'lat': 37.4210023197085,
                                             u'lng': -122.0857151802915}}},
  u'place_id': u'ChIJ2eUgeAK6j4ARbn5u_wAGqWA',
  u'types': [u'street_address']}]
--------------------------------------------------------
[{u'address_components': [{u'long_name': u'277',
                           u'short_name': u'277',
                           u'types': [u'street_number']},
                          {u'long_name': u'Bedford Avenue',
                           u'short_name': u'Bedford Ave',
                           u'types': [u'route']},
                          {u'long_name': u'Williamsburg',
                           u'short_name': u'Williamsburg',
                           u'types': [u'neighborhood', u'political']},
                          {u'long_name': u'Brooklyn',
                           u'short_name': u'Brooklyn',
                           u'types': [u'political',
                                      u'sublocality',
                                      u'sublocality_level_1']},
                          {u'long_name': u'Kings County',
                           u'short_name': u'Kings County',
                           u'types': [u'administrative_area_level_2',
                                      u'political']},
                          {u'long_name': u'New York',
                           u'short_name': u'NY',
                           u'types': [u'administrative_area_level_1',
                                      u'political']},
                          {u'long_name': u'United States',
                           u'short_name': u'US',
                           u'types': [u'country', u'political']},
                          {u'long_name': u'11211',
                           u'short_name': u'11211',
                           u'types': [u'postal_code']}],
  u'formatted_address': u'277 Bedford Ave, Brooklyn, NY 11211, USA',
  u'geometry': {u'location': {u'lat': 40.714232, u'lng': -73.9612889},
                u'location_type': u'ROOFTOP',
                u'viewport': {u'northeast': {u'lat': 40.7155809802915,
                                             u'lng': -73.9599399197085},
                              u'southwest': {u'lat': 40.7128830197085,
                                             u'lng': -73.96263788029151}}},
  u'place_id': u'ChIJd8BlQ2BZwokRAFUEcm_qrcA',
  u'types': [u'street_address']},
 {u'address_components': [{u'long_name': u'Grand St/Bedford Av',
                           u'short_name': u'Grand St/Bedford Av',
                           u'types': [u'establishment',
                                      u'point_of_interest']},
                          {u'long_name': u'Williamsburg',
                           u'short_name': u'Williamsburg',
                           u'types': [u'neighborhood', u'political']},
                          {u'long_name': u'Brooklyn',
                           u'short_name': u'Brooklyn',
                           u'types': [u'political',
                                      u'sublocality',
                                      u'sublocality_level_1']},
                          {u'long_name': u'Kings County',
                           u'short_name': u'Kings County',
                           u'types': [u'administrative_area_level_2',
                                      u'political']},
                          {u'long_name': u'New York',
                           u'short_name': u'NY',
                           u'types': [u'administrative_area_level_1',
                                      u'political']},
                          {u'long_name': u'United States',
                           u'short_name': u'US',
                           u'types': [u'country', u'political']},
                          {u'long_name': u'11211',
                           u'short_name': u'11211',
                           u'types': [u'postal_code']}],
  u'formatted_address': u'Grand St/Bedford Av, Brooklyn, NY 11211, USA',
  u'geometry': {u'location': {u'lat': 40.714321, u'lng': -73.961151},
                u'location_type': u'APPROXIMATE',
                u'viewport': {u'northeast': {u'lat': 40.71566998029149,
                                             u'lng': -73.95980201970849},
                              u'southwest': {u'lat': 40.7129720197085,
                                             u'lng': -73.96249998029151}}},
  u'place_id': u'ChIJi27VXGBZwokRM8ErPyB91yk',
  u'types': [u'bus_station',
             u'establishment',
             u'point_of_interest',
             u'transit_station']},
 {u'address_components': [{u'long_name': u'Williamsburg',
                           u'short_name': u'Williamsburg',
                           u'types': [u'neighborhood', u'political']},
                          {u'long_name': u'Brooklyn',
                           u'short_name': u'Brooklyn',
                           u'types': [u'political',
                                      u'sublocality',
                                      u'sublocality_level_1']},
                          {u'long_name': u'New York',
                           u'short_name': u'New York',
                           u'types': [u'locality', u'political']},
                          {u'long_name': u'Kings County',
                           u'short_name': u'Kings County',
                           u'types': [u'administrative_area_level_2',
                                      u'political']},
                          {u'long_name': u'New York',
                           u'short_name': u'NY',
                           u'types': [u'administrative_area_level_1',
                                      u'political']},
                          {u'long_name': u'United States',
                           u'short_name': u'US',
                           u'types': [u'country', u'political']}],
  u'formatted_address': u'Williamsburg, Brooklyn, NY, USA',
  u'geometry': {u'bounds': {u'northeast': {u'lat': 40.7251773,
                                           u'lng': -73.936498},
                            u'southwest': {u'lat': 40.6979329,
                                           u'lng': -73.96984499999999}},
                u'location': {u'lat': 40.7081156, u'lng': -73.9570696},
                u'location_type': u'APPROXIMATE',
                u'viewport': {u'northeast': {u'lat': 40.7251773,
                                             u'lng': -73.936498},
                              u'southwest': {u'lat': 40.6979329,
                                             u'lng': -73.96984499999999}}},
  u'place_id': u'ChIJQSrBBv1bwokRbNfFHCnyeYI',
  u'types': [u'neighborhood', u'political']},
 {u'address_components': [{u'long_name': u'Brooklyn',
                           u'short_name': u'Brooklyn',
                           u'types': [u'political',
                                      u'sublocality',
                                      u'sublocality_level_1']},
                          {u'long_name': u'New York',
                           u'short_name': u'New York',
                           u'types': [u'locality', u'political']},
                          {u'long_name': u'Kings County',
                           u'short_name': u'Kings County',
                           u'types': [u'administrative_area_level_2',
                                      u'political']},
                          {u'long_name': u'New York',
                           u'short_name': u'NY',
                           u'types': [u'administrative_area_level_1',
                                      u'political']},
                          {u'long_name': u'United States',
                           u'short_name': u'US',
                           u'types': [u'country', u'political']}],
  u'formatted_address': u'Brooklyn, NY, USA',
  u'geometry': {u'bounds': {u'northeast': {u'lat': 40.739446,
                                           u'lng': -73.8333651},
                            u'southwest': {u'lat': 40.551042,
                                           u'lng': -74.05663}},
                u'location': {u'lat': 40.6781784, u'lng': -73.9441579},
                u'location_type': u'APPROXIMATE',
                u'viewport': {u'northeast': {u'lat': 40.739446,
                                             u'lng': -73.8333651},
                              u'southwest': {u'lat': 40.551042,
                                             u'lng': -74.05663}}},
  u'place_id': u'ChIJCSF8lBZEwokRhngABHRcdoI',
  u'types': [u'political', u'sublocality', u'sublocality_level_1']},
 {u'address_components': [{u'long_name': u'New York',
                           u'short_name': u'New York',
                           u'types': [u'locality', u'political']},
                          {u'long_name': u'New York',
                           u'short_name': u'NY',
                           u'types': [u'administrative_area_level_1',
                                      u'political']},
                          {u'long_name': u'United States',
                           u'short_name': u'US',
                           u'types': [u'country', u'political']}],
  u'formatted_address': u'New York, NY, USA',
  u'geometry': {u'bounds': {u'northeast': {u'lat': 40.9175771,
                                           u'lng': -73.70027209999999},
                            u'southwest': {u'lat': 40.4773991,
                                           u'lng': -74.25908989999999}},
                u'location': {u'lat': 40.7127837, u'lng': -74.0059413},
                u'location_type': u'APPROXIMATE',
                u'viewport': {u'northeast': {u'lat': 40.9175771,
                                             u'lng': -73.70027209999999},
                              u'southwest': {u'lat': 40.4773991,
                                             u'lng': -74.25908989999999}}},
  u'place_id': u'ChIJOwg_06VPwokRYv534QaPC8g',
  u'types': [u'locality', u'political']},
 {u'address_components': [{u'long_name': u'11211',
                           u'short_name': u'11211',
                           u'types': [u'postal_code']},
                          {u'long_name': u'Brooklyn',
                           u'short_name': u'Brooklyn',
                           u'types': [u'political',
                                      u'sublocality',
                                      u'sublocality_level_1']},
                          {u'long_name': u'New York',
                           u'short_name': u'New York',
                           u'types': [u'locality', u'political']},
                          {u'long_name': u'New York',
                           u'short_name': u'NY',
                           u'types': [u'administrative_area_level_1',
                                      u'political']},
                          {u'long_name': u'United States',
                           u'short_name': u'US',
                           u'types': [u'country', u'political']}],
  u'formatted_address': u'Brooklyn, NY 11211, USA',
  u'geometry': {u'bounds': {u'northeast': {u'lat': 40.7280089,
                                           u'lng': -73.9207299},
                            u'southwest': {u'lat': 40.7008331,
                                           u'lng': -73.9644697}},
                u'location': {u'lat': 40.7093358, u'lng': -73.9565551},
                u'location_type': u'APPROXIMATE',
                u'viewport': {u'northeast': {u'lat': 40.7280089,
                                             u'lng': -73.9207299},
                              u'southwest': {u'lat': 40.7008331,
                                             u'lng': -73.9644697}}},
  u'place_id': u'ChIJvbEjlVdZwokR4KapM3WCFRw',
  u'types': [u'postal_code']},
 {u'address_components': [{u'long_name': u'Kings County',
                           u'short_name': u'Kings County',
                           u'types': [u'administrative_area_level_2',
                                      u'political']},
                          {u'long_name': u'New York',
                           u'short_name': u'NY',
                           u'types': [u'administrative_area_level_1',
                                      u'political']},
                          {u'long_name': u'United States',
                           u'short_name': u'US',
                           u'types': [u'country', u'political']}],
  u'formatted_address': u'Kings County, NY, USA',
  u'geometry': {u'bounds': {u'northeast': {u'lat': 40.739446,
                                           u'lng': -73.8333651},
                            u'southwest': {u'lat': 40.551042,
                                           u'lng': -74.05663}},
                u'location': {u'lat': 40.6528762,
                              u'lng': -73.95949399999999},
                u'location_type': u'APPROXIMATE',
                u'viewport': {u'northeast': {u'lat': 40.739446,
                                             u'lng': -73.8333651},
                              u'southwest': {u'lat': 40.551042,
                                             u'lng': -74.05663}}},
  u'place_id': u'ChIJOwE7_GTtwokRs75rhW4_I6M',
  u'types': [u'administrative_area_level_2', u'political']},
 {u'address_components': [{u'long_name': u'New York-Northern New Jersey-Long Island, NY-NJ-PA',
                           u'short_name': u'New York-Northern New Jersey-Long Island, NY-NJ-PA',
                           u'types': [u'political']},
                          {u'long_name': u'United States',
                           u'short_name': u'US',
                           u'types': [u'country', u'political']}],
  u'formatted_address': u'New York-Northern New Jersey-Long Island, NY-NJ-PA, USA',
  u'geometry': {u'bounds': {u'northeast': {u'lat': 41.6018065,
                                           u'lng': -71.856214},
                            u'southwest': {u'lat': 39.49853299999999,
                                           u'lng': -75.3585939}},
                u'location': {u'lat': 40.9590293, u'lng': -74.0300122},
                u'location_type': u'APPROXIMATE',
                u'viewport': {u'northeast': {u'lat': 41.6018065,
                                             u'lng': -71.856214},
                              u'southwest': {u'lat': 39.49853299999999,
                                             u'lng': -75.3585939}}},
  u'place_id': u'ChIJ3YJV4PRWwokRFFI21ZrHXtQ',
  u'types': [u'political']},
 {u'address_components': [{u'long_name': u'New York Metropolitan Area',
                           u'short_name': u'New York Metropolitan Area',
                           u'types': [u'political']},
                          {u'long_name': u'United States',
                           u'short_name': u'US',
                           u'types': [u'country', u'political']}],
  u'formatted_address': u'New York Metropolitan Area, USA',
  u'geometry': {u'bounds': {u'northeast': {u'lat': 42.0809059,
                                           u'lng': -71.777491},
                            u'southwest': {u'lat': 39.475198,
                                           u'lng': -75.3587649}},
                u'location': {u'lat': 40.7127761, u'lng': -74.0059544},
                u'location_type': u'APPROXIMATE',
                u'viewport': {u'northeast': {u'lat': 42.0809059,
                                             u'lng': -71.777491},
                              u'southwest': {u'lat': 39.475198,
                                             u'lng': -75.3587649}}},
  u'place_id': u'ChIJ-5Z24NaGwokRiMh4Rj8FNMo',
  u'types': [u'political']},
 {u'address_components': [{u'long_name': u'New York',
                           u'short_name': u'NY',
                           u'types': [u'administrative_area_level_1',
                                      u'political']},
                          {u'long_name': u'United States',
                           u'short_name': u'US',
                           u'types': [u'country', u'political']}],
  u'formatted_address': u'New York, USA',
  u'geometry': {u'bounds': {u'northeast': {u'lat': 44.9781473,
                                           u'lng': -73.0877489},
                            u'southwest': {u'lat': 40.6546144,
                                           u'lng': -78.6568941}},
                u'location': {u'lat': 43.2994285,
                              u'lng': -74.21793260000001},
                u'location_type': u'APPROXIMATE',
                u'viewport': {u'northeast': {u'lat': 44.9781473,
                                             u'lng': -73.0877489},
                              u'southwest': {u'lat': 40.6546144,
                                             u'lng': -78.6568941}}},
  u'place_id': u'ChIJqaUj8fBLzEwRZ5UY3sHGz90',
  u'types': [u'administrative_area_level_1', u'political']},
 {u'address_components': [{u'long_name': u'United States',
                           u'short_name': u'US',
                           u'types': [u'country', u'political']}],
  u'formatted_address': u'United States',
  u'geometry': {u'bounds': {u'northeast': {u'lat': 71.3867745,
                                           u'lng': -66.9502861},
                            u'southwest': {u'lat': 18.9106771,
                                           u'lng': 172.4458954}},
                u'location': {u'lat': 37.09024, u'lng': -95.712891},
                u'location_type': u'APPROXIMATE',
                u'viewport': {u'northeast': {u'lat': 49.38, u'lng': -66.94},
                              u'southwest': {u'lat': 25.82,
                                             u'lng': -124.39}}},
  u'place_id': u'ChIJCzYy5IS16lQRQrfeQ5K5Oxw',
  u'types': [u'country', u'political']}]
