[{u'address_components': [{u'long_name': u'55',
                           u'short_name': u'55',
                           u'types': [u'street_number']},
                          {u'long_name': u'Rua Doutor Alfredo Weyne',
                           u'short_name': u'Rua Dr. Alfredo Weyne',
                           u'types': [u'route']},
                          {u'long_name': u'Fatima',
                           u'short_name': u'Fatima',
                           u'types': [u'political',
                                      u'sublocality',
                                      u'sublocality_level_1']},
                          {u'long_name': u'Fortaleza',
                           u'short_name': u'Fortaleza',
                           u'types': [u'locality', u'political']},
                          {u'long_name': u'Fortaleza',
                           u'short_name': u'Fortaleza',
                           u'types': [u'administrative_area_level_2',
                                      u'political']},
                          {u'long_name': u'Cear\xe1',
                           u'short_name': u'CE',
                           u'types': [u'administrative_area_level_1',
                                      u'political']},
                          {u'long_name': u'Brazil',
                           u'short_name': u'BR',
                           u'types': [u'country', u'political']},
                          {u'long_name': u'60415',
                           u'short_name': u'60415',
                           u'types': [u'postal_code',
                                      u'postal_code_prefix']}],
  u'formatted_address': u'Rua Dr. Alfredo Weyne, 55 - Fatima, Fortaleza - CE, Brazil',
  u'geometry': {u'location': {u'lat': -3.7548986, u'lng': -38.5331491},
                u'location_type': u'ROOFTOP',
                u'viewport': {u'northeast': {u'lat': -3.753549619708497,
                                             u'lng': -38.5318001197085},
                              u'southwest': {u'lat': -3.756247580291502,
                                             u'lng': -38.53449808029149}}},
  u'partial_match': True,
  u'place_id': u'ChIJU8u5ESRJxwcR46IW2T60Ozo',
  u'types': [u'street_address']},
 {u'address_components': [{u'long_name': u'Condom\xednio Manuela Mendes',
                           u'short_name': u'Condom\xednio Manuela Mendes',
                           u'types': [u'premise']},
                          {u'long_name': u'55',
                           u'short_name': u'55',
                           u'types': [u'street_number']},
                          {u'long_name': u'Rua Doutor Alfredo Weyne',
                           u'short_name': u'Rua Dr. Alfredo Weyne',
                           u'types': [u'route']},
                          {u'long_name': u'Fatima',
                           u'short_name': u'Fatima',
                           u'types': [u'political',
                                      u'sublocality',
                                      u'sublocality_level_1']},
                          {u'long_name': u'Fortaleza',
                           u'short_name': u'Fortaleza',
                           u'types': [u'locality', u'political']},
                          {u'long_name': u'Fortaleza',
                           u'short_name': u'Fortaleza',
                           u'types': [u'administrative_area_level_2',
                                      u'political']},
                          {u'long_name': u'Cear\xe1',
                           u'short_name': u'CE',
                           u'types': [u'administrative_area_level_1',
                                      u'political']},
                          {u'long_name': u'Brazil',
                           u'short_name': u'BR',
                           u'types': [u'country', u'political']},
                          {u'long_name': u'60415-065',
                           u'short_name': u'60415-065',
                           u'types': [u'postal_code']}],
  u'formatted_address': u'Condom\xednio Manuela Mendes - Rua Dr. Alfredo Weyne, 55 - Fatima, Fortaleza - CE, 60415-065, Brazil',
  u'geometry': {u'location': {u'lat': -3.7549154, u'lng': -38.533159},
                u'location_type': u'ROOFTOP',
                u'viewport': {u'northeast': {u'lat': -3.753566419708497,
                                             u'lng': -38.5318100197085},
                              u'southwest': {u'lat': -3.756264380291502,
                                             u'lng': -38.5345079802915}}},
  u'partial_match': True,
  u'place_id': u'ChIJMemygyZJxwcRMZ3RR4yX_Jk',
  u'types': [u'premise']}]
Fortaleza
